POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNhbGlzZGVubmljcyIsImlkIjoiNjljMDQzNmZiMDk1YWIwMDk0MGEyNGVlIiwiaWF0IjoxNzc0MjY5MTkxfQ.ThIlZcdOUVNqtbIsqmVZ_v5j_7BuYhpB18L5wRNH39s

{
    "title": "Ultra White", 
    "author": "Monster Energy",
    "url": "http://google.com",
    "likes": "254"

}

###

DELETE http://localhost:3003/api/blogs/69c140058458488e6669bda0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNhbGlzZGVubmljcyIsImlkIjoiNjljMDQzNmZiMDk1YWIwMDk0MGEyNGVlIiwiaWF0IjoxNzc0MjY5MTkxfQ.ThIlZcdOUVNqtbIsqmVZ_v5j_7BuYhpB18L5wRNH39s

###
GET http://localhost:3003/api/blogs/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNhbGlzZGVubmljcyIsImlkIjoiNjljMDQzNmZiMDk1YWIwMDk0MGEyNGVlIiwiaWF0IjoxNzc0MjY5MTkxfQ.ThIlZcdOUVNqtbIsqmVZ_v5j_7BuYhpB18L5wRNH39s
